/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.test.avro_study.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MyDirectory extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MyDirectory\",\"namespace\":\"com.test.avro_study.model\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"doc\":\"目录名\"},{\"name\":\"path\",\"type\":\"string\",\"doc\":\"目录路径\"},{\"name\":\"fileCount\",\"type\":\"int\",\"doc\":\"目录下文件个数\"},{\"name\":\"isEmpty\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** 目录名 */
  @Deprecated public java.lang.CharSequence name;
  /** 目录路径 */
  @Deprecated public java.lang.CharSequence path;
  /** 目录下文件个数 */
  @Deprecated public int fileCount;
  @Deprecated public boolean isEmpty;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public MyDirectory() {}

  /**
   * All-args constructor.
   */
  public MyDirectory(java.lang.CharSequence name, java.lang.CharSequence path, java.lang.Integer fileCount, java.lang.Boolean isEmpty) {
    this.name = name;
    this.path = path;
    this.fileCount = fileCount;
    this.isEmpty = isEmpty;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return path;
    case 2: return fileCount;
    case 3: return isEmpty;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: path = (java.lang.CharSequence)value$; break;
    case 2: fileCount = (java.lang.Integer)value$; break;
    case 3: isEmpty = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * 目录名   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * 目录名   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'path' field.
   * 目录路径   */
  public java.lang.CharSequence getPath() {
    return path;
  }

  /**
   * Sets the value of the 'path' field.
   * 目录路径   * @param value the value to set.
   */
  public void setPath(java.lang.CharSequence value) {
    this.path = value;
  }

  /**
   * Gets the value of the 'fileCount' field.
   * 目录下文件个数   */
  public java.lang.Integer getFileCount() {
    return fileCount;
  }

  /**
   * Sets the value of the 'fileCount' field.
   * 目录下文件个数   * @param value the value to set.
   */
  public void setFileCount(java.lang.Integer value) {
    this.fileCount = value;
  }

  /**
   * Gets the value of the 'isEmpty' field.
   */
  public java.lang.Boolean getIsEmpty() {
    return isEmpty;
  }

  /**
   * Sets the value of the 'isEmpty' field.
   * @param value the value to set.
   */
  public void setIsEmpty(java.lang.Boolean value) {
    this.isEmpty = value;
  }

  /** Creates a new MyDirectory RecordBuilder */
  public static com.test.avro_study.model.MyDirectory.Builder newBuilder() {
    return new com.test.avro_study.model.MyDirectory.Builder();
  }
  
  /** Creates a new MyDirectory RecordBuilder by copying an existing Builder */
  public static com.test.avro_study.model.MyDirectory.Builder newBuilder(com.test.avro_study.model.MyDirectory.Builder other) {
    return new com.test.avro_study.model.MyDirectory.Builder(other);
  }
  
  /** Creates a new MyDirectory RecordBuilder by copying an existing MyDirectory instance */
  public static com.test.avro_study.model.MyDirectory.Builder newBuilder(com.test.avro_study.model.MyDirectory other) {
    return new com.test.avro_study.model.MyDirectory.Builder(other);
  }
  
  /**
   * RecordBuilder for MyDirectory instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MyDirectory>
    implements org.apache.avro.data.RecordBuilder<MyDirectory> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence path;
    private int fileCount;
    private boolean isEmpty;

    /** Creates a new Builder */
    private Builder() {
      super(com.test.avro_study.model.MyDirectory.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.test.avro_study.model.MyDirectory.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.path)) {
        this.path = data().deepCopy(fields()[1].schema(), other.path);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.fileCount)) {
        this.fileCount = data().deepCopy(fields()[2].schema(), other.fileCount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.isEmpty)) {
        this.isEmpty = data().deepCopy(fields()[3].schema(), other.isEmpty);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing MyDirectory instance */
    private Builder(com.test.avro_study.model.MyDirectory other) {
            super(com.test.avro_study.model.MyDirectory.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.path)) {
        this.path = data().deepCopy(fields()[1].schema(), other.path);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.fileCount)) {
        this.fileCount = data().deepCopy(fields()[2].schema(), other.fileCount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.isEmpty)) {
        this.isEmpty = data().deepCopy(fields()[3].schema(), other.isEmpty);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.test.avro_study.model.MyDirectory.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.test.avro_study.model.MyDirectory.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'path' field */
    public java.lang.CharSequence getPath() {
      return path;
    }
    
    /** Sets the value of the 'path' field */
    public com.test.avro_study.model.MyDirectory.Builder setPath(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.path = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'path' field has been set */
    public boolean hasPath() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'path' field */
    public com.test.avro_study.model.MyDirectory.Builder clearPath() {
      path = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'fileCount' field */
    public java.lang.Integer getFileCount() {
      return fileCount;
    }
    
    /** Sets the value of the 'fileCount' field */
    public com.test.avro_study.model.MyDirectory.Builder setFileCount(int value) {
      validate(fields()[2], value);
      this.fileCount = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'fileCount' field has been set */
    public boolean hasFileCount() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'fileCount' field */
    public com.test.avro_study.model.MyDirectory.Builder clearFileCount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'isEmpty' field */
    public java.lang.Boolean getIsEmpty() {
      return isEmpty;
    }
    
    /** Sets the value of the 'isEmpty' field */
    public com.test.avro_study.model.MyDirectory.Builder setIsEmpty(boolean value) {
      validate(fields()[3], value);
      this.isEmpty = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'isEmpty' field has been set */
    public boolean hasIsEmpty() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'isEmpty' field */
    public com.test.avro_study.model.MyDirectory.Builder clearIsEmpty() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public MyDirectory build() {
      try {
        MyDirectory record = new MyDirectory();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.path = fieldSetFlags()[1] ? this.path : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.fileCount = fieldSetFlags()[2] ? this.fileCount : (java.lang.Integer) defaultValue(fields()[2]);
        record.isEmpty = fieldSetFlags()[3] ? this.isEmpty : (java.lang.Boolean) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
