/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.test.pojo;
@SuppressWarnings("all")
/** 一周的枚举 */
@org.apache.avro.specific.AvroGenerated
public enum   Day {
  MON, TUE, WEN, THR, FRI, SAT, SUN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Day\",\"namespace\":\"com.test.pojo\",\"doc\":\"一周的枚举\",\"symbols\":[\"MON\",\"TUE\",\"WEN\",\"THR\",\"FRI\",\"SAT\",\"SUN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
