/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.test.avro_study;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Greeting extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Greeting\",\"namespace\":\"com.test.avro_study\",\"fields\":[{\"name\":\"msg\",\"type\":[\"null\",\"string\"],\"doc\":\"消息\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** 消息 */
  @Deprecated public java.lang.CharSequence msg;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Greeting() {}

  /**
   * All-args constructor.
   */
  public Greeting(java.lang.CharSequence msg) {
    this.msg = msg;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return msg;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: msg = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'msg' field.
   * 消息   */
  public java.lang.CharSequence getMsg() {
    return msg;
  }

  /**
   * Sets the value of the 'msg' field.
   * 消息   * @param value the value to set.
   */
  public void setMsg(java.lang.CharSequence value) {
    this.msg = value;
  }

  /** Creates a new Greeting RecordBuilder */
  public static com.test.avro_study.Greeting.Builder newBuilder() {
    return new com.test.avro_study.Greeting.Builder();
  }
  
  /** Creates a new Greeting RecordBuilder by copying an existing Builder */
  public static com.test.avro_study.Greeting.Builder newBuilder(com.test.avro_study.Greeting.Builder other) {
    return new com.test.avro_study.Greeting.Builder(other);
  }
  
  /** Creates a new Greeting RecordBuilder by copying an existing Greeting instance */
  public static com.test.avro_study.Greeting.Builder newBuilder(com.test.avro_study.Greeting other) {
    return new com.test.avro_study.Greeting.Builder(other);
  }
  
  /**
   * RecordBuilder for Greeting instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Greeting>
    implements org.apache.avro.data.RecordBuilder<Greeting> {

    private java.lang.CharSequence msg;

    /** Creates a new Builder */
    private Builder() {
      super(com.test.avro_study.Greeting.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.test.avro_study.Greeting.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.msg)) {
        this.msg = data().deepCopy(fields()[0].schema(), other.msg);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Greeting instance */
    private Builder(com.test.avro_study.Greeting other) {
            super(com.test.avro_study.Greeting.SCHEMA$);
      if (isValidValue(fields()[0], other.msg)) {
        this.msg = data().deepCopy(fields()[0].schema(), other.msg);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'msg' field */
    public java.lang.CharSequence getMsg() {
      return msg;
    }
    
    /** Sets the value of the 'msg' field */
    public com.test.avro_study.Greeting.Builder setMsg(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.msg = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'msg' field has been set */
    public boolean hasMsg() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'msg' field */
    public com.test.avro_study.Greeting.Builder clearMsg() {
      msg = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Greeting build() {
      try {
        Greeting record = new Greeting();
        record.msg = fieldSetFlags()[0] ? this.msg : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
