/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.test.avro_study;

@SuppressWarnings("all")
/** 问候类 */
@org.apache.avro.specific.AvroGenerated
public interface Hello {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Hello\",\"namespace\":\"com.test.avro_study\",\"doc\":\"问候类\",\"types\":[{\"type\":\"record\",\"name\":\"Greeting\",\"fields\":[{\"name\":\"msg\",\"type\":[\"null\",\"string\"],\"doc\":\"消息\",\"default\":null}]},{\"type\":\"error\",\"name\":\"Curse\",\"fields\":[{\"name\":\"msg\",\"type\":\"string\",\"doc\":\"异常消息\"}]}],\"messages\":{\"hello\":{\"error\":[\"Curse\"],\"request\":[{\"name\":\"greeting\",\"type\":\"Greeting\"}],\"response\":\"Greeting\"}}}");
  com.test.avro_study.Greeting hello(com.test.avro_study.Greeting greeting) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** 问候类 */
  public interface Callback extends Hello {
    public static final org.apache.avro.Protocol PROTOCOL = com.test.avro_study.Hello.PROTOCOL;
    void hello(com.test.avro_study.Greeting greeting, org.apache.avro.ipc.Callback<com.test.avro_study.Greeting> callback) throws java.io.IOException;
  }
}