/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.test.avro_study.enums;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum MyFileType { 
  FileType, DirectoryType  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MyFileType\",\"namespace\":\"com.test.avro_study.enums\",\"symbols\":[\"FileType\",\"DirectoryType\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
